# fly.toml app configuration file generated for claude on 2023-04-21T19:48:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "claude"
primary_region = "iad"

[build]
